"""
Export manager: JSON and PDF/Markdown report generation.
"""
import json
import io
import html
from datetime import datetime


def to_json(results: dict) -> str:
    """Serialize full pipeline results to JSON string."""
    return json.dumps(results, indent=2, ensure_ascii=False)


def to_markdown_report(results: dict, context: dict) -> str:
    """Generate a clean Markdown report from pipeline results."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    papers = results.get("papers", [])
    gaps = results.get("gaps", [])
    proposals = results.get("proposals", [])
    communities = results.get("communities", [])

    lines = []
    lines.append(f"# Research Gap Analysis Report")
    lines.append(f"*Generated: {now}*\n")

    lines.append(f"## Research Context")
    lines.append(f"- **Domain:** {context.get('domain', 'N/A')}")
    lines.append(f"- **Interest:** {context.get('interest', 'N/A')}")
    lines.append(f"- **Gap Type:** {context.get('gap_type', 'N/A')}\n")

    lines.append(f"## Papers Analyzed ({len(papers)})")
    for i, p in enumerate(papers, 1):
        wiki = p.get("wiki", {})
        lines.append(f"\n### {i}. {wiki.get('title', p.get('filename', f'Paper {i}'))}")
        contribs = wiki.get("contributions", [])
        if contribs:
            lines.append("**Key Contributions:**")
            for c in contribs[:3]:
                lines.append(f"- {c}")
        limitations = wiki.get("limitations", [])
        if limitations:
            lines.append("**Stated Limitations:**")
            for lim in limitations[:3]:
                lines.append(f"- {lim}")

    if communities:
        lines.append(f"\n## Knowledge Communities ({len(communities)})")
        for i, c in enumerate(communities, 1):
            lines.append(f"\n### Community {i}: {c.get('theme', 'N/A')}")
            lines.append(c.get("summary", ""))

    lines.append(f"\n## Identified Research Gaps ({len(gaps)})")
    for i, g in enumerate(gaps, 1):
        status = g.get("validation_status", "unknown")
        status_emoji = {"open": "🟢", "partial": "🟡", "solved": "🔴"}.get(status, "⚪")
        lines.append(f"\n### Gap {i}: {g.get('title', 'Untitled')} {status_emoji}")
        lines.append(f"**Type:** {g.get('gap_type', 'N/A')} | **Confidence:** {g.get('confidence', 'N/A')} | **Status:** {status}")
        lines.append(f"\n{g.get('description', '')}")
        evidence = g.get("evidence", [])
        if evidence:
            lines.append("\n**Evidence:**")
            for e in evidence:
                lines.append(f"- {e}")
        existing = g.get("existing_papers", [])
        if existing:
            lines.append("\n**Related Existing Work:**")
            for ep in existing[:2]:
                lines.append(f"- {ep.get('title', 'N/A')} ({ep.get('year', 'N/A')})")

    lines.append(f"\n## Research Proposals ({len(proposals)})")
    for i, p in enumerate(proposals, 1):
        lines.append(f"\n### Proposal {i}: {p.get('title', 'Untitled')}")
        lines.append(f"**Confidence:** {p.get('confidence', 'N/A')}")
        lines.append(f"\n**Problem Statement:** {p.get('problem_statement', '')}")
        lines.append(f"\n**Proposed Methodology:** {p.get('methodology', '')}")
        lines.append(f"\n**Novelty:** {p.get('novelty', '')}")
        builds_on = p.get("builds_on", [])
        if builds_on:
            lines.append(f"\n**Builds On:** {', '.join(builds_on)}")

    lines.append(f"\n---\n*Report generated by Research Gap Analyzer*")
    return "\n".join(lines)


def _clean(value) -> str:
    return str(value or "").replace("\n", " ").strip()


def to_pdf_report(results: dict, context: dict) -> bytes:
    """Generate an enterprise-style PDF report from structured results."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
    )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        rightMargin=0.6 * inch,
        leftMargin=0.6 * inch,
        topMargin=0.6 * inch,
        bottomMargin=0.6 * inch,
    )
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="ReportTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=22,
        leading=26,
        textColor=colors.HexColor("#111827"),
        spaceAfter=14,
    ))
    styles.add(ParagraphStyle(
        name="Section",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=16,
        textColor=colors.HexColor("#1f2937"),
        spaceBefore=12,
        spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        name="Small",
        parent=styles["BodyText"],
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#4b5563"),
    ))

    papers = results.get("papers", [])
    refs = results.get("ref_papers", [])
    ref_summary = results.get("ref_summary", {})
    graph = results.get("graph", {})
    gaps = results.get("gaps", [])
    proposals = results.get("proposals", [])

    story = [
        Paragraph("Research Gap Analysis Report", styles["ReportTitle"]),
        Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles["Small"]),
        Spacer(1, 10),
    ]

    summary_rows = [
        ["Domain", _clean(context.get("domain", "N/A"))],
        ["Interest", _clean(context.get("interest", "N/A"))],
        ["Papers analyzed", str(len(papers))],
        ["References extracted", str(ref_summary.get("total", len(refs)))],
        ["Graph entities", str(graph.get("stats", {}).get("entity_count", 0))],
        ["Research gaps", str(len(gaps))],
        ["Proposals", str(len(proposals))],
    ]
    summary = Table(summary_rows, colWidths=[1.9 * inch, 5.0 * inch])
    summary.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f3f4f6")),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#111827")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#d1d5db")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story += [Paragraph("Executive Summary", styles["Section"]), summary]

    story.append(Paragraph("Papers Analyzed", styles["Section"]))
    for i, p in enumerate(papers[:10], 1):
        wiki = p.get("wiki", {})
        story.append(Paragraph(f"{i}. {_clean(wiki.get('title') or p.get('filename'))}", styles["Heading4"]))
        for lim in wiki.get("limitations", [])[:3]:
            story.append(Paragraph(f"Limitation: {_clean(lim)}", styles["Small"]))

    story.append(Paragraph("Reference Corpus", styles["Section"]))
    story.append(Paragraph(
        f"{ref_summary.get('total', len(refs))} references; "
        f"{ref_summary.get('tier2_abstract', 0)} with abstracts; "
        f"{ref_summary.get('tier3_title', 0)} title-only.",
        styles["BodyText"],
    ))
    if refs:
        ref_rows = [["Title", "Year", "Tier", "Source"]]
        for r in refs[:30]:
            ref_rows.append([
                Paragraph(_clean(r.get("title", "Unknown"))[:120], styles["Small"]),
                _clean(r.get("year", "")),
                str(r.get("tier", "")),
                _clean(r.get("source", "")),
            ])
        tbl = Table(ref_rows, colWidths=[4.1 * inch, 0.6 * inch, 0.45 * inch, 1.1 * inch], repeatRows=1)
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#d1d5db")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("PADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(tbl)

    story.append(PageBreak())
    story.append(Paragraph("Knowledge Graph", styles["Section"]))
    stats = graph.get("stats", {})
    story.append(Paragraph(
        f"Entities: {stats.get('entity_count', 0)}; relationships: {stats.get('relationship_count', 0)}; "
        f"communities: {stats.get('community_count', 0)}.",
        styles["BodyText"],
    ))
    for e in graph.get("entities", [])[:25]:
        story.append(Paragraph(
            f"{_clean(e.get('name'))} ({_clean(e.get('type'))}, {_clean(e.get('importance'))})",
            styles["Small"],
        ))

    story.append(Paragraph("Research Gaps", styles["Section"]))
    for i, gap in enumerate(gaps, 1):
        story.append(Paragraph(f"{i}. {_clean(gap.get('title', 'Untitled'))}", styles["Heading4"]))
        story.append(Paragraph(_clean(gap.get("description", "")), styles["BodyText"]))
        story.append(Paragraph(
            f"Status: {_clean(gap.get('validation_status'))}; confidence: {_clean(gap.get('confidence'))}",
            styles["Small"],
        ))

    story.append(Paragraph("Recommended Proposals", styles["Section"]))
    for i, proposal in enumerate(proposals, 1):
        story.append(Paragraph(f"{i}. {_clean(proposal.get('title', 'Untitled'))}", styles["Heading4"]))
        story.append(Paragraph(_clean(proposal.get("problem_statement", "")), styles["BodyText"]))
        story.append(Paragraph(f"Methodology: {_clean(proposal.get('methodology', ''))}", styles["Small"]))

    doc.build(story)
    buf.seek(0)
    return buf.read()


REPORT_NARRATIVE_PROMPT = """You are writing an enterprise research report for a research lead.

Use only the structured facts provided. Do not invent citations, counts, methods, or findings.
Write concise, executive-friendly prose.

Return ONLY JSON:
{
  "executive_summary": ["3-5 concise bullets"],
  "research_objective": "1 paragraph",
  "corpus_overview": "1 paragraph",
  "knowledge_graph_summary": "1 paragraph",
  "risk_and_limitations": ["4-6 bullets"],
  "closing_recommendation": "1 paragraph"
}"""


def _safe_list(value, limit=5):
    return value[:limit] if isinstance(value, list) else []


def _report_summary_payload(results: dict, context: dict) -> dict:
    graph = results.get("graph", {})
    stats = graph.get("stats", {})
    refs = results.get("ref_papers", [])
    gaps = results.get("gaps", [])
    proposals = results.get("proposals", [])
    papers = results.get("papers", [])
    return {
        "context": context,
        "counts": {
            "papers": len(papers),
            "references": len(refs),
            "references_with_abstract": results.get("ref_summary", {}).get("tier2_abstract", 0),
            "graph_entities": stats.get("entity_count", 0),
            "graph_relationships": stats.get("relationship_count", 0),
            "gaps": len(gaps),
            "proposals": len(proposals),
        },
        "papers": [
            {
                "title": p.get("wiki", {}).get("title") or p.get("filename"),
                "limitations": _safe_list(p.get("wiki", {}).get("limitations", []), 3),
                "contributions": _safe_list(p.get("wiki", {}).get("contributions", []), 3),
            }
            for p in papers[:8]
        ],
        "top_references": [
            {
                "title": r.get("title"),
                "year": r.get("year"),
                "source": r.get("source"),
                "citations": r.get("citations", 0),
            }
            for r in refs[:12]
        ],
        "gaps": [
            {
                "title": g.get("title"),
                "status": g.get("validation_status"),
                "confidence": g.get("confidence"),
                "description": g.get("description"),
            }
            for g in gaps[:8]
        ],
        "proposals": [
            {
                "title": p.get("title"),
                "confidence": p.get("confidence"),
                "methodology": p.get("methodology"),
            }
            for p in proposals[:6]
        ],
        "graph_diagnostics": graph.get("diagnostics", {}),
        "ref_diagnostics": results.get("ref_diagnostics", {}),
    }


def generate_report_narrative(results: dict, context: dict, client=None) -> dict:
    """Generate LLM narrative with deterministic fallback."""
    fallback = {
        "executive_summary": [
            f"Analyzed {len(results.get('papers', []))} uploaded papers and {len(results.get('ref_papers', []))} extracted references.",
            f"Identified {len(results.get('gaps', []))} research gaps and {len(results.get('proposals', []))} recommended proposals.",
            "Reference and graph diagnostics are included so reviewers can audit the evidence base.",
        ],
        "research_objective": (
            f"The analysis focuses on {context.get('domain', 'the selected domain')} with interest in "
            f"{context.get('interest', 'the uploaded research corpus')}."
        ),
        "corpus_overview": (
            "The corpus combines uploaded full-text papers with extracted references enriched through academic metadata sources where available."
        ),
        "knowledge_graph_summary": (
            "The knowledge graph summarizes extracted concepts, methods, datasets, limitations, and relationships across the analyzed papers."
        ),
        "risk_and_limitations": [
            "Reference enrichment depends on external academic APIs and network availability.",
            "LLM-generated summaries should be reviewed against source evidence before submission.",
            "Title-only references may have lower confidence than references with abstracts.",
            "Graph quality depends on the quality of PDF text extraction and LLM JSON output.",
        ],
        "closing_recommendation": (
            "Use the validated gaps and proposal shortlist as a starting point for research planning, then manually review high-value references."
        ),
    }
    if not client:
        return fallback
    try:
        raw = client.chat_json(
            REPORT_NARRATIVE_PROMPT,
            json.dumps(_report_summary_payload(results, context), indent=2, default=str),
            max_tokens=1800,
        )
        parsed = json.loads(raw)
        if isinstance(parsed, dict):
            return {**fallback, **parsed}
    except Exception:
        return fallback
    return fallback


def _esc(value) -> str:
    return html.escape(str(value or ""))


def _bullets(items) -> str:
    return "".join(f"<li>{_esc(item)}</li>" for item in (items or []))


def _status_class(status: str) -> str:
    return {
        "open": "good",
        "partial": "warn",
        "solved": "bad",
        "pending": "muted",
    }.get(str(status or "").lower(), "muted")


def to_enterprise_html_report(results: dict, context: dict, narrative: dict | None = None) -> str:
    """Build a polished standalone HTML report."""
    narrative = narrative or generate_report_narrative(results, context)
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    papers = results.get("papers", [])
    refs = results.get("ref_papers", [])
    graph = results.get("graph", {})
    graph_stats = graph.get("stats", {})
    gaps = results.get("gaps", [])
    proposals = results.get("proposals", [])
    trace = results.get("pipeline_trace", [])
    ref_diag = results.get("ref_diagnostics", {})
    graph_diag = graph.get("diagnostics", {})

    paper_rows = "".join(
        f"<tr><td>{i}</td><td>{_esc(p.get('wiki', {}).get('title') or p.get('filename'))}</td>"
        f"<td>{_esc('; '.join(_safe_list(p.get('wiki', {}).get('contributions', []), 2)))}</td>"
        f"<td>{_esc('; '.join(_safe_list(p.get('wiki', {}).get('limitations', []), 2)))}</td></tr>"
        for i, p in enumerate(papers, 1)
    )
    ref_rows = "".join(
        f"<tr><td>{i}</td><td>{_esc(r.get('title'))}</td><td>{_esc(r.get('year'))}</td>"
        f"<td>{_esc(r.get('doi'))}</td><td>{_esc(r.get('source'))}</td><td>{_esc(r.get('citations', 0))}</td></tr>"
        for i, r in enumerate(refs[:80], 1)
    )
    entity_rows = "".join(
        f"<tr><td>{_esc(e.get('name'))}</td><td>{_esc(e.get('type'))}</td>"
        f"<td>{_esc(e.get('importance'))}</td><td>{_esc(', '.join(e.get('papers', [])[:3]))}</td></tr>"
        for e in graph.get("entities", [])[:80]
    )
    rel_rows = "".join(
        f"<tr><td>{_esc(r.get('source'))}</td><td>{_esc(r.get('relation'))}</td>"
        f"<td>{_esc(r.get('target'))}</td><td>{_esc(r.get('paper'))}</td></tr>"
        for r in graph.get("relationships", [])[:80]
    )
    gap_cards = "".join(
        f"<div class='item'><div><span class='pill {_status_class(g.get('validation_status'))}'>{_esc(g.get('validation_status'))}</span>"
        f"<span class='pill'>{_esc(g.get('confidence'))} confidence</span></div>"
        f"<h3>{_esc(g.get('title'))}</h3><p>{_esc(g.get('description'))}</p>"
        f"<h4>Evidence</h4><ul>{_bullets(g.get('evidence', [])[:5])}</ul>"
        f"<h4>Validation</h4><p>{_esc(g.get('validation_reasoning'))}</p></div>"
        for g in gaps
    )
    proposal_cards = "".join(
        f"<div class='item'><h3>{_esc(p.get('title'))}</h3>"
        f"<p><strong>Problem:</strong> {_esc(p.get('problem_statement'))}</p>"
        f"<p><strong>Methodology:</strong> {_esc(p.get('methodology'))}</p>"
        f"<p><strong>Novelty:</strong> {_esc(p.get('novelty'))}</p></div>"
        for p in proposals
    )
    trace_rows = "".join(
        f"<tr><td>{i}</td><td>{_esc(t.get('stage'))}</td><td>{_esc(t.get('inputs'))}</td><td>{_esc(t.get('outputs'))}</td></tr>"
        for i, t in enumerate(trace, 1)
    )

    return f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Research Gap Analysis Report</title>
  <style>
    body {{ margin:0; background:#f6f8fb; color:#111827; font-family: Inter, Segoe UI, Arial, sans-serif; }}
    .page {{ max-width:1120px; margin:0 auto; padding:40px 48px; background:white; }}
    .cover {{ border-bottom:1px solid #d9e1ec; padding:54px 0 38px; }}
    .eyebrow {{ color:#2563eb; font-size:12px; font-weight:700; letter-spacing:.08em; text-transform:uppercase; }}
    h1 {{ font-size:38px; line-height:1.12; margin:12px 0 14px; }}
    h2 {{ font-size:22px; margin:34px 0 12px; padding-top:8px; border-top:1px solid #e5e7eb; }}
    h3 {{ font-size:16px; margin:12px 0 6px; }}
    h4 {{ font-size:12px; color:#475467; text-transform:uppercase; letter-spacing:.06em; margin:12px 0 4px; }}
    p, li, td, th {{ font-size:13px; line-height:1.55; }}
    .meta {{ color:#667085; }}
    .grid {{ display:grid; grid-template-columns:repeat(4,1fr); gap:12px; margin:22px 0; }}
    .stat {{ border:1px solid #d9e1ec; border-radius:8px; padding:14px; background:#f8fafc; }}
    .stat .num {{ font-size:24px; font-weight:700; color:#1d4ed8; }}
    .stat .lbl {{ color:#667085; font-size:12px; }}
    table {{ width:100%; border-collapse:collapse; margin:12px 0 18px; }}
    th {{ background:#f1f5f9; text-align:left; color:#344054; }}
    th, td {{ border:1px solid #e5e7eb; padding:8px 10px; vertical-align:top; }}
    .item {{ border:1px solid #d9e1ec; border-radius:8px; padding:14px 16px; margin:12px 0; background:#fff; }}
    .pill {{ display:inline-block; border:1px solid #d0d5dd; border-radius:999px; padding:2px 8px; font-size:11px; color:#344054; margin-right:6px; }}
    .pill.good {{ color:#047857; border-color:#a7f3d0; background:#ecfdf5; }}
    .pill.warn {{ color:#b45309; border-color:#fed7aa; background:#fffbeb; }}
    .pill.bad {{ color:#b91c1c; border-color:#fecaca; background:#fef2f2; }}
    .pill.muted {{ color:#475467; background:#f9fafb; }}
    .note {{ border-left:3px solid #2563eb; background:#eff6ff; padding:10px 12px; margin:10px 0; }}
    @media print {{ body {{ background:white; }} .page {{ padding:28px; }} h2 {{ break-after:avoid; }} .item, table {{ break-inside:avoid; }} }}
  </style>
</head>
<body>
<main class="page">
  <section class="cover">
    <div class="eyebrow">Research Gap Analyzer</div>
    <h1>Research Gap Analysis Report</h1>
    <p class="meta">Generated {now}</p>
    <p><strong>Domain:</strong> {_esc(context.get('domain'))} &nbsp; <strong>Gap focus:</strong> {_esc(context.get('gap_type'))}</p>
  </section>

  <section>
    <h2>Executive Summary</h2>
    <ul>{_bullets(narrative.get('executive_summary', []))}</ul>
  </section>

  <section>
    <h2>Research Objective</h2>
    <p>{_esc(narrative.get('research_objective'))}</p>
    <div class="note"><strong>Research interest:</strong> {_esc(context.get('interest'))}</div>
  </section>

  <section>
    <h2>Corpus Overview</h2>
    <p>{_esc(narrative.get('corpus_overview'))}</p>
    <div class="grid">
      <div class="stat"><div class="num">{len(papers)}</div><div class="lbl">Uploaded papers</div></div>
      <div class="stat"><div class="num">{len(refs)}</div><div class="lbl">Extracted references</div></div>
      <div class="stat"><div class="num">{graph_stats.get('entity_count',0)}</div><div class="lbl">Graph entities</div></div>
      <div class="stat"><div class="num">{len(gaps)}</div><div class="lbl">Research gaps</div></div>
    </div>
  </section>

  <section>
    <h2>Papers Analyzed</h2>
    <table><thead><tr><th>#</th><th>Paper</th><th>Key contributions</th><th>Limitations</th></tr></thead><tbody>{paper_rows}</tbody></table>
  </section>

  <section>
    <h2>Reference Corpus Summary</h2>
    <p>Raw citations: {_esc(ref_diag.get('raw_entries',0))}; LLM parsed: {_esc(ref_diag.get('structured_entries',0))}; fallback parsed: {_esc(ref_diag.get('fallback_entries',0))}; duplicates skipped: {_esc(ref_diag.get('duplicates_skipped',0))}.</p>
    <table><thead><tr><th>#</th><th>Title</th><th>Year</th><th>DOI</th><th>Source</th><th>Citations</th></tr></thead><tbody>{ref_rows}</tbody></table>
  </section>

  <section>
    <h2>Knowledge Graph Summary</h2>
    <p>{_esc(narrative.get('knowledge_graph_summary'))}</p>
    <p>Entities: {graph_stats.get('entity_count',0)}; relationships: {graph_stats.get('relationship_count',0)}; communities: {graph_stats.get('community_count',0)}; fallback used: {_esc(graph_diag.get('used_fallback', False))}.</p>
  </section>

  <section>
    <h2>Key Research Gaps</h2>
    {gap_cards}
  </section>

  <section>
    <h2>Validation Evidence</h2>
    <p>Each gap is tagged with academic-search validation status and supporting/related papers where found.</p>
    {''.join(f"<div class='item'><h3>{_esc(g.get('title'))}</h3><p><strong>Status:</strong> {_esc(g.get('validation_status'))}</p><p>{_esc(g.get('validation_reasoning'))}</p><ul>{_bullets([p.get('title') for p in g.get('existing_papers', [])[:5]])}</ul></div>" for g in gaps)}
  </section>

  <section>
    <h2>Recommended Research Proposals</h2>
    {proposal_cards}
  </section>

  <section>
    <h2>Risks and Limitations</h2>
    <ul>{_bullets(narrative.get('risk_and_limitations', []))}</ul>
    <p>{_esc(narrative.get('closing_recommendation'))}</p>
  </section>

  <section>
    <h2>Appendix: Extracted References</h2>
    <table><thead><tr><th>#</th><th>Title</th><th>Year</th><th>DOI</th><th>Source</th><th>Citations</th></tr></thead><tbody>{ref_rows}</tbody></table>
  </section>

  <section>
    <h2>Appendix: Graph Entities and Relationships</h2>
    <h3>Entities</h3>
    <table><thead><tr><th>Name</th><th>Type</th><th>Importance</th><th>Papers</th></tr></thead><tbody>{entity_rows}</tbody></table>
    <h3>Relationships</h3>
    <table><thead><tr><th>Source</th><th>Relation</th><th>Target</th><th>Paper</th></tr></thead><tbody>{rel_rows}</tbody></table>
  </section>

  <section>
    <h2>Appendix: Pipeline Audit</h2>
    <table><thead><tr><th>#</th><th>Stage</th><th>Inputs</th><th>Outputs</th></tr></thead><tbody>{trace_rows}</tbody></table>
  </section>
</main>
</body>
</html>"""


def to_enterprise_pdf_report(results: dict, context: dict, narrative: dict | None = None) -> bytes:
    """Generate a PDF with the same report sections as the HTML report."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak

    narrative = narrative or generate_report_narrative(results, context)
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, rightMargin=0.55*inch,
                            leftMargin=0.55*inch, topMargin=0.55*inch,
                            bottomMargin=0.55*inch)
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="ReportTitle2", parent=styles["Title"], fontSize=22,
                              leading=26, textColor=colors.HexColor("#111827")))
    styles.add(ParagraphStyle(name="Section2", parent=styles["Heading2"], fontSize=13,
                              leading=16, textColor=colors.HexColor("#1f2937"), spaceBefore=12))
    styles.add(ParagraphStyle(name="Small2", parent=styles["BodyText"], fontSize=8, leading=10))

    def para(text, style="BodyText"):
        return Paragraph(_esc(text), styles[style])

    def bullet_list(items):
        return [Paragraph(f"- {_esc(item)}", styles["BodyText"]) for item in (items or [])]

    def simple_table(rows, widths):
        tbl = Table(rows, colWidths=widths, repeatRows=1)
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e5e7eb")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#d1d5db")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("PADDING", (0, 0), (-1, -1), 4),
        ]))
        return tbl

    papers = results.get("papers", [])
    refs = results.get("ref_papers", [])
    graph = results.get("graph", {})
    gaps = results.get("gaps", [])
    proposals = results.get("proposals", [])
    ref_diag = results.get("ref_diagnostics", {})
    story = [
        Paragraph("Research Gap Analysis Report", styles["ReportTitle2"]),
        para(f"Generated {datetime.now().strftime('%Y-%m-%d %H:%M')}", "Small2"),
        para(f"Domain: {context.get('domain','')} | Gap focus: {context.get('gap_type','')}"),
        Spacer(1, 10),
        Paragraph("Executive Summary", styles["Section2"]),
        *bullet_list(narrative.get("executive_summary", [])),
        Paragraph("Research Objective", styles["Section2"]),
        para(narrative.get("research_objective", "")),
        Paragraph("Corpus Overview", styles["Section2"]),
        para(narrative.get("corpus_overview", "")),
    ]

    metrics = [
        ["Metric", "Value"],
        ["Uploaded papers", str(len(papers))],
        ["Extracted references", str(len(refs))],
        ["Graph entities", str(graph.get("stats", {}).get("entity_count", 0))],
        ["Research gaps", str(len(gaps))],
        ["Proposals", str(len(proposals))],
    ]
    story += [simple_table(metrics, [2.5*inch, 4.0*inch])]

    story.append(Paragraph("Papers Analyzed", styles["Section2"]))
    paper_rows = [["#", "Paper", "Limitations"]]
    for i, p in enumerate(papers[:12], 1):
        wiki = p.get("wiki", {})
        paper_rows.append([
            str(i),
            Paragraph(_esc(wiki.get("title") or p.get("filename")), styles["Small2"]),
            Paragraph(_esc("; ".join(_safe_list(wiki.get("limitations", []), 2))), styles["Small2"]),
        ])
    story.append(simple_table(paper_rows, [0.35*inch, 3.2*inch, 3.0*inch]))

    story.append(Paragraph("Reference Corpus Summary", styles["Section2"]))
    story.append(para(
        f"Raw citations: {ref_diag.get('raw_entries',0)}; LLM parsed: {ref_diag.get('structured_entries',0)}; "
        f"fallback parsed: {ref_diag.get('fallback_entries',0)}."
    ))
    ref_rows = [["#", "Title", "Year", "Source"]]
    for i, r in enumerate(refs[:35], 1):
        ref_rows.append([str(i), Paragraph(_esc(r.get("title")), styles["Small2"]),
                         _esc(r.get("year")), _esc(r.get("source"))])
    story.append(simple_table(ref_rows, [0.35*inch, 4.3*inch, 0.7*inch, 1.2*inch]))

    story.append(PageBreak())
    story.append(Paragraph("Knowledge Graph Summary", styles["Section2"]))
    story.append(para(narrative.get("knowledge_graph_summary", "")))
    story.append(para(
        f"Entities: {graph.get('stats',{}).get('entity_count',0)}; relationships: {graph.get('stats',{}).get('relationship_count',0)}; communities: {graph.get('stats',{}).get('community_count',0)}."
    ))

    story.append(Paragraph("Key Research Gaps", styles["Section2"]))
    for i, g in enumerate(gaps, 1):
        story.append(para(f"{i}. {g.get('title','Untitled')} ({g.get('validation_status','')}, {g.get('confidence','')} confidence)", "Heading4"))
        story.append(para(g.get("description", "")))
        story.append(para(f"Validation: {g.get('validation_reasoning','')}", "Small2"))

    story.append(Paragraph("Validation Evidence", styles["Section2"]))
    for g in gaps:
        story.append(para(g.get("title", ""), "Heading4"))
        for p in g.get("existing_papers", [])[:3]:
            story.append(para(f"{p.get('title','')} ({p.get('year','')}) - {p.get('source','')}", "Small2"))

    story.append(Paragraph("Recommended Research Proposals", styles["Section2"]))
    for i, p in enumerate(proposals, 1):
        story.append(para(f"{i}. {p.get('title','Untitled')}", "Heading4"))
        story.append(para(p.get("problem_statement", "")))
        story.append(para(f"Methodology: {p.get('methodology','')}", "Small2"))

    story.append(Paragraph("Risks and Limitations", styles["Section2"]))
    story.extend(bullet_list(narrative.get("risk_and_limitations", [])))

    story.append(PageBreak())
    story.append(Paragraph("Appendix: Graph Entities and Relationships", styles["Section2"]))
    entity_rows = [["Name", "Type", "Importance"]]
    for e in graph.get("entities", [])[:50]:
        entity_rows.append([Paragraph(_esc(e.get("name")), styles["Small2"]), _esc(e.get("type")), _esc(e.get("importance"))])
    story.append(simple_table(entity_rows, [4.2*inch, 1.2*inch, 1.1*inch]))

    story.append(Paragraph("Appendix: Pipeline Audit", styles["Section2"]))
    trace_rows = [["#", "Stage", "Output"]]
    for i, t in enumerate(results.get("pipeline_trace", []), 1):
        trace_rows.append([str(i), Paragraph(_esc(t.get("stage")), styles["Small2"]),
                           Paragraph(_esc(t.get("outputs")), styles["Small2"])])
    story.append(simple_table(trace_rows, [0.35*inch, 2.4*inch, 3.8*inch]))

    doc.build(story)
    buf.seek(0)
    return buf.read()
